CREATE TABLE Events (
	Id INT AUTO_INCREMENT NOT NULL,
	Title VARCHAR(255) NOT NULL,
	Date DATETIME NOT NULL,
	Description VARCHAR(255) NOT NULL,
	Observation VARCHAR(255),
	CONSTRAINT PK_Events PRIMARY KEY (id)
);